name: "[dev] Check Pull Request"

on:
 pull_request:
  types: ["opened", "edited", "reopened", "synchronize", "ready_for_review", "review_requested"]
  paths-ignore:
   - "**/*.md"
   - ".vscode/**"

jobs:
 Build:
  uses: ./.github/workflows/build.yml
