name: "[master] Release"

on:
 push:
  branches:
   - "master"
  paths-ignore:
   - "**/*.md"
   - ".vscode/**"

jobs:
 Build:
  uses: ./.github/workflows/build.yml

 Release:
  name: Draft latest release on GitHub
  needs: Build
  runs-on: ubuntu-latest

  steps:
   - name: Download All Artifacts
     uses: actions/download-artifact@v4
     with:
      name: luna-artifacts
      path: ./dist/

   - name: Publish latest draft release on GitHub
     uses: marvinpinto/action-automatic-releases@latest
     with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      automatic_release_tag: latest
      title: Latest Release
      files: ./dist/luna.zip
