name: "[dev] Release"

on:
 push:
  branches:
   - dev
  paths-ignore:
   - "**/*.md"
   - ".vscode/**"

jobs:
 Build:
  uses: ./.github/workflows/build.yml

 Release:
  name: Release dev on GitHub
  needs: Build
  runs-on: ubuntu-latest

  steps:
   - name: Download All Artifacts
     uses: actions/download-artifact@v4
     with:
      name: luna-artifacts
      path: ./dist/

   - name: Get version from package.json
     run: |
      VERSION=$(jq -r .version package.json)
      echo "VERSION=${VERSION}-dev" >> $GITHUB_ENV

   - name: Publish dev release on GitHub
     uses: marvinpinto/action-automatic-releases@latest
     with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      automatic_release_tag: ${{ env.VERSION }}
      prerelease: true
      title: Release ${{ env.VERSION }}
      files: ./dist/luna.zip
